# Generated by Django 2.1.4 on 2019-02-06 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('serial', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Serial')),
                ('typee', models.CharField(choices=[('G', 'Seguimiento'), ('P', 'Valor en mapa'), ('M', 'Valor en modulo')], max_length=1, verbose_name='Tipo de dispositivo')),
                ('date_register', models.DateField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
