# Generated by Django 2.1.4 on 2019-02-14 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(verbose_name='Latitud')),
                ('longitude', models.FloatField(verbose_name='Longitud')),
                ('altitude', models.FloatField(verbose_name='Altitud')),
                ('date_register', models.DateField(auto_now_add=True, verbose_name='Fecha de registro')),
            ],
        ),
        migrations.AlterField(
            model_name='device',
            name='typee',
            field=models.CharField(choices=[('G', 'Seguimiento'), ('S', 'Valor en mapa'), ('M', 'Valor en modulo')], max_length=1, verbose_name='Tipo de dispositivo'),
        ),
        migrations.AddField(
            model_name='position',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.Device', verbose_name=''),
        ),
    ]
