# Generated by Django 2.1.4 on 2019-02-22 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_auto_20190222_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='altitude',
        ),
    ]
