# Generated by Django 2.1.4 on 2019-03-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_remove_position_altitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='date_register',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro'),
        ),
    ]
