# Generated by Django 2.1.7 on 2019-03-01 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkShop',
            fields=[
                ('key', models.CharField(default='DEFAULT', max_length=15, primary_key=True, serialize=False, verbose_name='code')),
                ('link', models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Enlace')),
            ],
            options={
                'verbose_name': 'Enlace de tienda',
            },
        ),
    ]
