# Generated by Django 2.1.4 on 2019-03-08 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkshop',
            name='link',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Enlace'),
        ),
    ]
